import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";

import "@/src/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}
      >
        <div className="flex flex-col items-center justify-start w-full min-h-screen font-medium">
          <main className="flex flex-col content-center items-start justify-start w-full max-w-3xl p-4 gap-4">
            <h1 className="font-mono text-4xl font-bold tracking-tight p-2">Noticount</h1>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
